kind: pipeline

steps:
- name: hello
  image: alpine
  commands:
  - echo hello
  - echo world
---
kind: pipeline

steps:
- name: hello
  image: alpine
  commands:
  - This is tagged commit

trigger:
  event:
  - tag
